### ISSUE TITLE
About compilation of benchmarks

### ISSUE THREAD

**Issue by heejin5178** [mitdbg/treeline#110]
Hello.

I tried to compile benchmark by using "`cmake -DCMAKE_BUILD_TYPE=Release -DTL_BUILD_BENCHMARKS=ON .. && make -j`".
But it failed because it couldn't find `ycsbr` repository.
What's the additional task for compilation?

**Comment by geoffxy** [comment]
Hi - thanks for your interest in TreeLine! We're working on releasing these benchmark dependencies this week and will follow up once they are available.

**Comment by heejin5178** [comment]
Thank you :)

**Comment by geoffxy** [comment]
@heejin5178 Following up - please try compiling again on the latest code on `master`. We've released the additional dependencies so it should work now.
