### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by heejin5178** [mitdbg/treeline#112]
Hello.

After YCSB added, I tried to compile benchmark with using `cmake -DCMAKE_BUILD_TYPE=Release -DTL_BUILD_BENCHMARKS=ON .. && make -j`.
However, I still suffered from compilation failure. 

Error message is shown below.
![treeline_compile_error](https://user-images.githubusercontent.com/30685666/208857270-89f20d36-9df1-4170-8aa5-fd3e9fb488b9.png)

How can I fix the error?

And during compilation, I found that `leanstore` couldn't added in `_deps` folder.
Therefore, I forced files of `leanstore` located in the folder.
How can I make it automatically?

If I missed something, please let me know :)

Thank you.

**Comment by geoffxy** [comment]
Have you pulled the latest code? `leanstore` shouldn't be added to the `_deps` directory; it's checked in as a subproject under `third_party`.

Are you compiling the code with a compiler and standard library that have support for C++17 features? The error looks like the linker can't find definitions for `std::filesystem` related code, which was added in C++17.

**Comment by heejin5178** [comment]
First of all, thank you for fast reply.
As you said, I found that I used C++14, so I updated it.
But still, I suffered from compilation failure because of `leanstore`.

Error message looks like below.
![treeline_compile_error](https://user-images.githubusercontent.com/30685666/209055758-f6dcb051-dfd1-4351-ab20-f7d69cfd83e7.png)

I think `CMakeList.txt` in `third_party/leanstore` has to be fixed.. 
Did I miss something?

Thank you.

**Comment by geoffxy** [comment]
> I think CMakeList.txt in third_party/leanstore has to be fixed..

Thanks for pointing this out! Yes - it looks like we didn't catch this problem with these paths since we were doing an incremental recompile.

I pushed a new commit to `master` that should fix the problem. Can you try compiling again using the latest code?

**Comment by heejin5178** [comment]
I found that this version has no problem with `leanstore`.

Still, I found there is problem related to Masstree compilation.
It cannot find `config.h` in `third_party/masstree` folder.
I think compilation skipped `./configure` in masstree folder.

I fixed it manually by using `./configure` in `third_party/masstree` folder. 
After that, the folder has `config.h`.

Plus, although it can be my individual environment, compiler cannot find `dl`.
Therefore, I make `dl` linked by fixing `CMakeLists.txt`.

Thank you for fixing the issue! :)

**Comment by geoffxy** [comment]
Glad you got it working! That's interesting - we had set up `CMakeLists.txt` to automatically run `./configure` for Masstree, and it seemed to work fine on our side. Could you let us know what version of CMake you are using? Also, what change did you need to make to link `dl`?
