### ISSUE TITLE
ycsb_runner unavailable

### ISSUE THREAD

**Issue by levitar64** [mitdbg/treeline#114]
I am working on scripts under `scripts/e2e_perf` and trying to generate ycsb traces using `scripts/generate_ycsb_traces.sh`. It requires that I clone `ycsb_runner` from azure but the destination azure page suggests the project is closed due to inactivity. Is it possible to make it available once more?

**Comment by geoffxy** [comment]
Hey @levitar64 - `ycsb_runner` is the legacy name of `ycsbr`. So when the script refers to cloning the repository on Azure, you can just point it to a cloned copy of [`ycsbr`](https://github.com/mitdbg/ycsbr/) and it should work. Please let us know if you run into any issues getting it running.

**Comment by geoffxy** [comment]
Another thing: you may find it easier to use `ycsbr` to generate and run a YCSB-like workload instead of recording a trace from the YCSB tool. `ycsbr` takes in a `.yml` file that specifies the workload; we have examples of the YCSB workloads specified in this way [here](https://github.com/mitdbg/treeline/blob/master/scripts/e2e_custom/ycsb/workloads/a.yml). The `run_custom` executable will take these workload files and run them against TreeLine.

**Comment by levitar64** [comment]
Thank you! I find it. And now I am trying to generate traces by running `./generate_ycsb_traces.sh ../../build/_deps/ycsbr-src`. Then an error occur which repeats the following message 6 times:

```
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl site.ycsb:core -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
[ERROR]  Attempting to generate a classpath from Maven failed with return code '1'. The output from Maven follows, try running 'mvn -DskipTests package dependency:build=classpath' on your own and correct errors.

mvn output:
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: site.ycsb:core @ 
[ERROR] Could not find the selected project in the reactor: site.ycsb:core -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

The YCSB executables are correctly added to my `$PATH` and the `experiment_config.sh` is also set.

**Comment by geoffxy** [comment]
This looks like an issue with the `ycsb` executable. Try seeing if you can run it independently outside of the script.
