### ISSUE TITLE
e2e_perf scripts outdated

### ISSUE THREAD

**Issue by levitar64** [mitdbg/treeline#115]
I'm trying to run benchmarks under `scripts/e2e_perf`. However, there are some issues with these scripts:

1. The `build_benchmarks.sh` executes `cmake` with a nonexistent option `LLSM_BUILD_BENCHMARKS`. I guess it should be changed to `TL_BUILD_BENCHMARKS`.
2. The `build_benchmarks.sh` executes `make` with the target `ycsb`, which, however, is not found in the `Makefile` under `build` folder.
3. Scripts under subdirectories `synth_write` and `ycsb` try to launch programs `./bench/synth_write` and `./bench/ycsb` respectively, but in reality `synth_write` is moved to `microbench` subdirectory and `ycsb` does not exist at all.

**Comment by geoffxy** [comment]
Yes, thanks for reporting. These are legacy scripts. The primary TreeLine YCSB benchmarks are under `scripts/ycsb_v2/`.

If you need access to the `ycsb` executable under `bench`, you can run against commit 2a0936775838b66ccb1faa1c0f5dbb55bc55552d. (We deleted `ycsb.cc` and some other legacy code in commit 302b3f55c5dff92f4ca256d511b94209ee9aa617.)
